### ISSUE TITLE
It should allow a user to pass parameters directly.

### ISSUE THREAD

**Issue by smartepsh** [duffelhq/paginator#14]
Hi,
Because the front-end always pass a `map` with string keys, I think it should normalize params from a `map` since it expects a `keyword list` for parameters like [Scrivener](https://github.com/drewolson/scrivener).

There are two ways of doing this:
1. normalize params from map to keyword list
2. use map directly in config struct.

Which kind do you prefer?

**Comment by stevedomin** [comment]
Hello @smartepsh, sorry I missed this issue.

Just to be clear, you are talking about the options of the `paginate` function?

**Comment by stevedomin** [comment]
Re-closing this for now. Let me know if this is still an issue for you @smartepsh.
