### ISSUE TITLE
What is the purpose of `cursor_fields`

### ISSUE THREAD

**Issue by tadiou** [duffelhq/paginator#145]
I know that they're used to create a cursor, and then match on it, but why would you not just use `id` assuming `id` is a unique value?

you have `[:charged_at, :amount, :id]`, but assuming `:id` is unique, what's the value of adding the other two?

**Comment by jstewart** [comment]
If you're sorting by multiple columns, they must be used to create a keyset. They end up being part of a `WHERE` clause:

```
WHERE charged_at > ? AND amount > ?...
```

If you're sorting by those columns, you can't just say `WHERE id > ?` since the records are not in `id` order anymore when you sort on the other cols.

**Comment by sgerrand** [comment]
@jstewart, that's exactly right. Thanks for chiming in!

**Comment by thojanssens** [comment]
Sorry but I don't understand the answer, and I feel very dumb now lol

> If you're sorting by those columns, you can't just say WHERE id > ? since the records are not in id order anymore when you sort on the other cols.

The answer mentions that if we sort by `charged_at` and `amount`, we can't only filter on `id`.

I don't see why. We can definitely filter based on `id` (where) and order by other fields (order_by).

**Comment by thojanssens** [comment]
@tadiou @jstewart @sgerrand
