### ISSUE TITLE
Calling paginate with after: won't return all results and won't return new metadata.after in output

### ISSUE THREAD

**Issue by massetech** [duffelhq/paginator#23]
I try to use the dep to provide a load more button that a user can call N times.

When the page loads the first time I call:
`Repo.paginate(query, include_total_count: true, cursor_fields: [:priority, :parution_date, :id], limit: 2)`

Then I use the metadata.after to trigger a second call:
`Repo.paginate(query, after: cursor_after, cursor_fields: [:priority, :parution_date, :id], limit: 2)`

This time I get a metadata.before and a metadata.after = nil which doesn't give the opportunity to call again and again the method. 

Did I misunderstood the objective of the dep, or there should be a new metadata.after provided until there is no more records ?

**Comment by massetech** [comment]
I just noticed that using the after: cursor_after close I will get only 1 record in return.
There is certainly a problem in `Repo.paginate(after: metadata.after)`

**Comment by stevedomin** [comment]
hello @massetech, it seems like you are using the lib correctly, I'm not sure what's wrong.

Can you share a repo with the issue so that I can reproduce it locally by any chance?

**Comment by massetech** [comment]
Hi Steve

You can find the project [here](https://github.com/massetech/boncoin)
I am sorry this project has not been refactored yet and you might not be able to run it locally (I use quite a lot of variables).

I use Paginator on Boncoin.Contents module (path is boncoin/lib/boncoin/contents/contents.ex, you can search the list_announces_public function).

I test the cursor_after passed in params in order to call a first time (nil) or load more entries later. The call is triggered from the page by an Ajax api call (websockets are not available on GAE).

If you can't find the problem easily pls let me know I will try to reproduce on a simpler app.

**Comment by massetech** [comment]
Found the problem .

Everything works fine if I remove the WHERE close in my query
`  defp filter_announces_online(query \\ Announce) do
    from a in query,
      where: a.status == "ONLINE"
  end`

I think Paginator is supposed to support WHERE clauses right ?

**Comment by maartenvanvliet** [comment]
Are there null values in the status column?

**Comment by massetech** [comment]
No ; but there can be some in the parution_date ; that's why I use the WHERE clause  (status == "ONLINE" means the parution_date is not nil)

`Repo.paginate(query, after: cursor_after, include_total_count: true, cursor_fields: [:parution_date, :id], limit: 4)`

**Comment by massetech** [comment]
I found something ; everything works perfectly if I change this line
`order_by: [asc: a.priority, desc: a.parution_date, asc: a.id]`
by
`order_by: [asc: a.priority, asc: a.parution_date, asc: a.id]`

So the problem would come from the DESC option. The a.parution_date column contains NULL entries. I tried with and without tose empty fields, it doesn't change anything (it works when I use ASC option, it is broken when I use DESC)...

**Comment by massetech** [comment]
I found the problem

When ones uses DESC with order_by, it has to be fixed to DESC as well on 
`Repo.paginate(offer_query, include_total_count: true, cursor_fields: [:priority, :parution_date], sort_direction: :desc, limit: 4)`

This is not clear in the documentation (I had to go into debugging the dependency to find that out).
I think this sort_direction option in paginate function should be definable per column ; for now it is global so you can't combine ASC and DESC in query, making this impossible :
`order_by: [desc: a.priority, asc: a.parution_date, desc: a.id]`
