### ISSUE TITLE
Name collision with scrivener_ecto

### ISSUE THREAD

**Issue by lpil** [duffelhq/paginator#27]
Hello!

This library and `scrivener_ecto` both provide a metaprogrammed API that generates a `paginate` function on the user's Repo.

Give they share the same name what is the recommended method for taking advantage of both libraries in one application? Using multiple repos would result in multiple connection pools, which has performance implications.

Thanks,
Louis

**Comment by lpil** [comment]
Looking at the source code it looks like it would be easy to use this library without any macros.

If the construction of the of the `Config` struct and the checking of `config.cursor_fields` was done in `Paginator.paginate` it would remove the need for the metaprogramming while maintaining backwards compatibility for existing users.

Then users could use this library without macros by defining this one function on their macro:

```elixir
defmodule MyRepo do
  def my_paginate_function(queryable, opts \\ [], repo_opts \\ []) do
    defaults = []
    opts = Keyword.merge(defaults, opts)
    Paginator.paginate(queryable, opts, __MODULE__, repo_opts)
  end
end
```

**Comment by ShaneWilton** [comment]
This is also something I'm running into in production, and I think @lpil's solution looks elegant for our purposes at least :)

**Comment by stevedomin** [comment]
v0.5 is out with this change: https://hex.pm/packages/paginator/0.5.0

**Comment by lpil** [comment]
Wonderful, thank you!

Mind if I add the above example to the README?

**Comment by stevedomin** [comment]
No, of course not! Go for it.
