### ISSUE TITLE
Ecto3-RC

### ISSUE THREAD

**Issue by razz-matazz** [duffelhq/paginator#36]
Hello,

Can paginator already be used with Ecto3-RC?

**Comment by Nickforall** [comment]
We are using it with ecto 3.0 and haven't had any problems yet :)

**Comment by stevedomin** [comment]
Hi @razz-matazz, I haven't tried it yet but I believe it should work. I'll update `mix.exs` to allow it.

**Comment by van-mronov** [comment]
Hi guys! I made a PR for this issue, https://github.com/duffelhq/paginator/pull/40

**Comment by van-mronov** [comment]
Guys, what do think about that?

**Comment by stevedomin** [comment]
Thanks @van-mronov!

**Comment by stevedomin** [comment]
This has been merged in 
https://github.com/duffelhq/paginator/commit/cc022be58ba4b35e934cce304d5ffc1cc77e7559
