### ISSUE TITLE
Wierd behaviour

### ISSUE THREAD

**Issue by razz-matazz** [duffelhq/paginator#37]
I created a small test phoenix app because I had strange results within my main app. But I get wierd results here, too: I created a simple schema for Tickets containing a subject and a message, generated 100 entries (all message and subject fields contain the id) and this is what I put in my controller: 

> @paging_factor = 5
> query = from t in Ticket,
>             order_by: t.subject
>
>    ##### return the first 5 posts
>   page1 = Repo.paginate(query, cursor_fields: [:subject, :id], limit: @paging_factor)
 >   IO.puts "first take:"
 >   for item <- page1.entries do
  >    IO.puts item.message
  >  end

Output is:
1
2
3
4
5

So far so good. But now:

   > ##### assign the `after` cursor to a variable
   > cursor_after = page1.metadata.after

>    #####  return the next 5 posts
>    page2 = Repo.paginate(query, after: cursor_after, cursor_fields: [:subject, :id], limit: @paging_factor)
 >   IO.puts "Next take..."
 >   for item <- page2.entries do
 >     IO.puts item.message
 >   end

This results in this output:
7
8
9
10
11

So it skipped the 6th object (and evertime I use the next cursor.after it skips one object)... But now it gets really weird:
`
>    #####  assign the `before` cursor to a variable
>    cursor_before = page2.metadata.before

 >   #####  return the previous 5 posts (if no post was created in between it should be the same list as in our first call to `paginate`)
>    page3 = Repo.paginate(query, before: cursor_before, cursor_fields: [:subject, :id], limit: @paging_factor)
>    IO.puts "Now go back..."
 >   for item <- page3.entries do
  >    IO.puts item.message
  >  end

Result:
4
3
2
1
0

My deps are:
      {:phoenix, "~> 1.3.4"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:plug_cowboy, "~> 1.0"},
      {:paginator, "~> 0.5"}

**Comment by stevedomin** [comment]
@razz-matazz Hello! Can you share the source of your test application? I'll try to reproduce locally.

**Comment by razz-matazz** [comment]
I have created my first github repository ever therefore, I hope it works:
https://github.com/razz-matazz/testfield

Pls tell me when I can delete it.

**Comment by razz-matazz** [comment]
Did you have an opportunity to look at this?

**Comment by razz-matazz** [comment]
As this is my first issue I opened on github: Did I anything wrong so that nothing happens? To me it seems that paginator is ultimately broken...

**Comment by polvalente** [comment]
@razz-matazz I know this is a long standing issue but...
[In this line](https://github.com/razz-matazz/testfield/blob/f52703bc80902a9bdbbec6d815a25c2f99f5574e/lib/testfield_web/controllers/page_controller.ex#L26) you set the query with `order_by: [:subject]`, but tried to paginate with `[:id, :subject]`. I think that is the core of your problem.

**Comment by JackShannon** [comment]
@polvalente Thank you for digging this up. It solved a similar problem that I was having.

**Comment by razz-matazz** [comment]
@polvalente thanks :)
