### ISSUE TITLE
Update hex release / broken desc pagination in 0.6.0

### ISSUE THREAD

**Issue by leepfrog** [duffelhq/paginator#65]
I am attempting to paginate results in descending order, and with the version I've installed from Hex (0.6.0), the Paginator is encoding the same values for both before/after.  The cursor decodes to `[nil,nil]`.

It looks like this issue no longer exists on the master branch (I vendored this module into my project to test), however, there has not been a hex release with these changes.

**Comment by Nickforall** [comment]
Temporarily you can add the master branch as a dependency:
```
{:paginator, git: "https://github.com/duffelhq/paginator.git", branch: "master"}
```

**Comment by alex88** [comment]
I've seen that with desc also `total_count` and `total_count_cap_exceeded` are `nil`, is it expected?

**Comment by walu-lila** [comment]
It would be nice if a new release was updated in hex. Spent some time trying to figure out why sorting by `desc` was not working, only to later find this issue

**Comment by sgerrand** [comment]
👋 [Version 1.0.0](https://hex.pm/packages/paginator/1.0.0) of this package was released yesterday with the feature you reference. I'm glad to hear that you're finding it useful.

This release also contains an important security related patch, so I highly recommend that you update to this version as soon as possible.
