### ISSUE TITLE
Order by & preloads

### ISSUE THREAD

**Issue by Kaquadu** [duffelhq/paginator#66]
Hi,
My first question is how can I set order_by of some field? Let's say I've got such query:
```
defp compose_query({"order_by", "title_ascending"}, query) do
    order_by(query, [advert], advert.title)
end
```
Setting cursor fields to [title: :asc] doesn't work for me - it seems that somehow metadata is broken. `Repo.paginate` responses with first page with correct entries and `metadata` seems like this:
```
%Paginator.Page.Metadata{
  after: "g2wAAAABZAADbmlsag==", #this is wrong
  before: nil,
  limit: 4,
  total_count: 7,
  total_count_cap_exceeded: false
}
```
Any advices? 😄 

___

My second question is about sorting by preloaded association field. Let's say I've got an `advert` that belongs to `user` & `user` has many `adverts`. I'm trying to paginate adverts ordered by user name.

My question is if is this possible somehow?
I'm performing query, which looks like that:
```
defp compose_query({"order_by", "user_email_ascending"}, query) do
    join(query, :left, [advert], user in assoc(advert, :user))
    |> order_by([advert, user], user.email)
end
```
My guess would be, that I should set `cursor_fields` to `[[:user, :email]]`, but it doesn't work.

I really hope for a fast answer 😄

**Comment by udeesha** [comment]
Add sort_direction: :desc / sort_direction: :asc into paginate as an option.

Eg:-  Repo.paginate(query, include_total_count: true, cursor_fields: cursor_fields, sort_direction: :asc, limit: 15)

**Comment by Kaquadu** [comment]
Yea, thank you or answer. It would be nice to add a bit more info about `cursor_fields` in documentation :)
